name = "sahara-website"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

pages_build_output_dir = ".vercel/output/static"

[[d1_databases]]
binding = "DB"
database_name = "sahara-db"
database_id = "PASTE_YOUR_D1_DATABASE_ID_HERE"

[[r2_buckets]]
binding = "SAHARA_ASSETS"
bucket_name = "sahara-printer-files"
