-- Migration 002: Seed clients table with 93 default clients
-- Run: npx wrangler d1 execute sahara-db --remote --file=database/migrations/002_seed_clients.sql

INSERT OR REPLACE INTO clients (id, name, logoUrl, website, isActive, sortOrder) VALUES
('1', 'Emirates Global Aluminium', '', 'https://www.ega.com', 1, 1),
('2', 'Emirates Dubai', '', 'https://www.emirates.com', 1, 2),
('3', 'Flydubai', '', 'https://www.flydubai.com', 1, 3),
('4', 'Abu Dhabi National Oil Company', '', 'https://www.adnoc.ae', 1, 4),
('5', 'Mubadala', '', 'https://www.mubadala.com', 1, 5),
('6', 'Abu Dhabi Commercial Bank', '', 'https://www.adcb.com', 1, 6),
('7', 'First Abu Dhabi Bank', '', 'https://www.fabbank.com', 1, 7),
('8', 'Abu Dhabi Islamic Bank', '', 'https://www.adib.ae', 1, 8),
('9', 'Aldar Properties', '', 'https://www.aldar.com', 1, 9),
('10', 'Sharaf Group', '', 'https://www.sharafgroup.com', 1, 10),
('11', 'Al-Futtaim Group', '', 'https://www.alfuttaim.com', 1, 11),
('12', 'Almarai', '', 'https://www.almarai.com', 1, 12),
('13', 'Alshaya Group', '', 'https://www.alshaya.com', 1, 13),
('14', 'Aramco', '', 'https://www.aramco.com', 1, 14),
('15', 'Saudi Arabian Airlines', '', 'https://www.saudia.com', 1, 15),
('16', 'Qatar Airways', '', 'https://www.qatarairways.com', 1, 16),
('17', 'Qatar National Bank', '', 'https://www.qnb.com', 1, 17),
('18', 'Ooredoo', '', 'https://www.ooredoo.com', 1, 18),
('19', 'Vodafone Qatar', '', 'https://www.vodafone.qa', 1, 19),
('20', 'Kuwait Airways', '', 'https://www.kuwaitairways.com', 1, 20),
('21', 'National Bank of Kuwait', '', 'https://www.nbk.com', 1, 21),
('22', 'Kuwait Finance House', '', 'https://www.kfh.com', 1, 22),
('23', 'Zain Kuwait', '', 'https://www.zain.com', 1, 23),
('24', 'Oman Airways', '', 'https://www.omanair.com', 1, 24),
('25', 'Bank Muscat', '', 'https://www.bankmuscat.com', 1, 25),
('26', 'OQ', '', 'https://www.oq.com', 1, 26),
('27', 'Omantel', '', 'https://www.omantel.com', 1, 27),
('28', 'Bahrain National Gas', '', 'https://www.bngc.com', 1, 28),
('29', 'Bapco', '', 'https://www.bapco.gov.bh', 1, 29),
('30', 'Batelco', '', 'https://www.batelco.com', 1, 30),
('31', 'National Bank of Bahrain', '', 'https://www.nbb.com', 1, 31),
('32', 'Aluminum Bahrain', '', 'https://www.aluminium.com', 1, 32),
('33', 'Dubai Police', '', 'https://www.dubaipolice.gov.ae', 1, 33),
('34', 'Dubai Municipality', '', 'https://www.dm.gov.ae', 1, 34),
('35', 'RTA Dubai', '', 'https://www.rta.ae', 1, 35),
('36', 'DEWA', '', 'https://www.dewa.gov.ae', 1, 36),
('37', 'ADNOC Distribution', '', 'https://www.adnocdistribution.ae', 1, 37),
('38', 'Sharjah Electricity Authority', '', 'https://www.sea.gov.ae', 1, 38),
('39', 'Ajman Municipality', '', 'https://www.ajman.gov.ae', 1, 39),
('40', 'UAE Ministry of Interior', '', 'https://www.moi.gov.ae', 1, 40),
('41', 'UAE Ministry of Finance', '', 'https://www.mof.gov.ae', 1, 41),
('42', 'Dubai Health Authority', '', 'https://www.dha.gov.ae', 1, 42),
('43', 'SEHA', '', 'https://www.seha.ae', 1, 43),
('44', 'Mubadala Healthcare', '', 'https://www.mubadalahealthcare.com', 1, 44),
('45', 'American Hospital', '', 'https://www.american-hospital.org', 1, 45),
('46', 'Cleveland Clinic Abu Dhabi', '', 'https://www.clevelandclinicabudhabi.ae', 1, 46),
('47', 'Burjeel Hospital', '', 'https://www.burjeel.com', 1, 47),
('48', 'Aster DM Healthcare', '', 'https://www.asterdmhealthcare.com', 1, 48),
('49', 'NMC Healthcare', '', 'https://www.nmchealth.com', 1, 49),
('50', 'Mediclinic Middle East', '', 'https://www.mediclinic.ae', 1, 50),
('51', 'Abu Dhabi University', '', 'https://www.adu.ac.ae', 1, 51),
('52', 'American University of Sharjah', '', 'https://www.aus.edu', 1, 52),
('53', 'Khalifa University', '', 'https://www.ku.ac.ae', 1, 53),
('54', 'University of Dubai', '', 'https://www.ud.edu.ae', 1, 54),
('55', 'Higher Colleges of Technology', '', 'https://www.hct.ac.ae', 1, 55),
('56', 'Zayed University', '', 'https://www.zu.ac.ae', 1, 56),
('57', 'UAE University', '', 'https://www.uaeu.ac.ae', 1, 57),
('58', 'Emirates Academy of Hospitality', '', 'https://www.eah.edu.ae', 1, 58),
('59', 'Emaar Properties', '', 'https://www.emaar.com', 1, 59),
('60', 'Nakheel Properties', '', 'https://www.nakheel.com', 1, 60),
('61', 'Dubai Properties', '', 'https://www.dubaiproperties.com', 1, 61),
('62', 'Meydan', '', 'https://www.meydan.ae', 1, 62),
('63', 'Dubai Sports City', '', 'https://www.dubaisportscity.com', 1, 63),
('64', 'Dubai Silicon Oasis', '', 'https://www.dsio.gov.ae', 1, 64),
('65', 'Dubai Multi Commodities Centre', '', 'https://www.dmcc.ae', 1, 65),
('66', 'Dubai International Financial Centre', '', 'https://www.difc.ae', 1, 66),
('67', 'Abu Dhabi Global Market', '', 'https://www.adgm.com', 1, 67),
('68', 'Dubai Chamber of Commerce', '', 'https://www.dubaichamber.com', 1, 68),
('69', 'Abu Dhabi Chamber of Commerce', '', 'https://www.adchamber.com', 1, 69),
('70', 'Dubai Customs', '', 'https://www.dubaicustoms.gov.ae', 1, 70),
('71', 'Federal Customs Authority', '', 'https://www.fca.gov.ae', 1, 71),
('72', 'Trivago', '', 'https://www.trivago.com', 1, 72),
('73', 'Booking.com', '', 'https://www.booking.com', 1, 73),
('74', 'Ctrip', '', 'https://www.ctrip.com', 1, 74),
('75', 'MakeMyTrip', '', 'https://www.makemytrip.com', 1, 75),
('76', 'Serco', '', 'https://www.serco.com', 1, 76),
('77', 'Al Khaja', '', '', 1, 77),
('78', 'Gargash', '', '', 1, 78),
('79', 'Juma Al Majid', '', 'https://www.jumaalmajid.com', 1, 79),
('80', 'Al Fareej', '', '', 1, 80),
('81', 'Al Mulla', '', '', 1, 81),
('82', 'Yousif Al Mulla', '', '', 1, 82),
('83', 'Khazan', '', 'https://www.khazan.com', 1, 83),
('84', 'Jimared', '', '', 1, 84),
('85', 'Sahara', '', '', 1, 85),
('86', 'National Electronics', '', '', 1, 86),
('87', 'Al Safeer', '', '', 1, 87),
('88', 'Al Labeeb', '', '', 1, 88),
('89', 'Dubai Global', '', '', 1, 89),
('90', 'Al Ghaff', '', '', 1, 90),
('91', 'Al Hashmi', '', '', 1, 91),
('92', 'Al Mazroui', '', 'https://www.almazroui.com', 1, 92),
('93', 'Bin Brothers', '', '', 1, 93);
