-- Migration 012: Seed hardcoded FAQs into D1 for all pages using dynamic schemas
-- Uses INSERT OR IGNORE so existing admin-entered FAQs are never overwritten.

-- Homepage
INSERT OR IGNORE INTO faqs (id, pageSlug, question, answer, sortOrder, isActive, createdAt) VALUES
('seed-home-1','homepage','What is the duration of your printer rental plans?','We offer flexible rental periods starting from short-term event hire (1-7 days) to long-term corporate leases (12-36 months), all with included maintenance.',1,1,'2026-01-01T00:00:00.000Z'),
('seed-home-2','homepage','Do you provide on-site repair services?','Yes, our factory-certified technicians provide on-site repairs across all major service areas. We aim for a 4-hour response time for critical failures.',2,1,'2026-01-01T00:00:00.000Z'),
('seed-home-3','homepage','Are the spare parts and toners original?','Exclusively. Sahara only supplies OEM (Original Equipment Manufacturer) consumables and parts to ensure the longevity of your hardware.',3,1,'2026-01-01T00:00:00.000Z'),
('seed-home-4','homepage','Can I upgrade my rented equipment during the contract?','Absolutely. Our ''Growth Guard'' policy allows you to upgrade your fleet as your office printing demands increase without hefty termination fees.',4,1,'2026-01-01T00:00:00.000Z');

-- Printer Rental Dubai
INSERT OR IGNORE INTO faqs (id, pageSlug, question, answer, sortOrder, isActive, createdAt) VALUES
('seed-dubai-1','printer-rental-dubai','How much does printer rental cost in Dubai?','Printer rental in Dubai starts from AED 250/month for an A4 desktop printer. A3 multifunction photocopiers (print, copy, scan) start from AED 500/month. High-speed enterprise copiers for large offices range from AED 1,000-2,000/month. All plans include zero deposit, unlimited OEM toner, maintenance, and free delivery across Dubai.',1,1,'2026-01-01T00:00:00.000Z'),
('seed-dubai-2','printer-rental-dubai','Do you offer zero deposit printer rental in Dubai?','Yes. Sahara offers zero deposit printer rental for qualified Dubai businesses. There is no upfront security deposit — you pay only the monthly rental. This applies to standard 12-36 month contracts for established businesses.',2,1,'2026-01-01T00:00:00.000Z'),
('seed-dubai-3','printer-rental-dubai','How fast can you deliver a rented printer to my Dubai office?','We offer same-day delivery to most Dubai districts including Business Bay, DIFC, JLT, Marina, Sheikh Zayed Road, and Deira. Next-day delivery is standard for all other Dubai locations. Our engineers handle the full network setup on delivery day at no extra charge.',3,1,'2026-01-01T00:00:00.000Z'),
('seed-dubai-4','printer-rental-dubai','What printer brands do you rent in Dubai?','We rent Canon imageRUNNER ADVANCE, Kyocera TASKalfa, HP LaserJet Enterprise, Ricoh MP series, and Xerox AltaLink in Dubai. Canon and Kyocera are our most popular brands due to their proven reliability in UAE climate conditions.',4,1,'2026-01-01T00:00:00.000Z'),
('seed-dubai-5','printer-rental-dubai','What is your emergency repair response time in Dubai?','Our average emergency repair response time in Dubai is 4 hours. For critical rental clients in Business Bay, DIFC, and Downtown Dubai, we maintain a priority dispatch queue with 2-hour target response. If a repair exceeds 24 hours, we deliver a loaner machine at no charge.',5,1,'2026-01-01T00:00:00.000Z'),
('seed-dubai-6','printer-rental-dubai','Is toner included in the Dubai printer rental price?','Yes — unlimited genuine OEM toner is included in all Sahara rental plans across Dubai. We remotely monitor toner levels and replenish proactively — you never need to order consumables or worry about running out mid-print.',6,1,'2026-01-01T00:00:00.000Z'),
('seed-dubai-7','printer-rental-dubai','Can I rent a printer for a short-term event or exhibition in Dubai?','Yes. We supply printers and photocopiers for Dubai exhibitions, DWTC events, trade shows, hotel functions, and temporary office setups. Short-term rentals are available from 1 day to 3 months.',7,1,'2026-01-01T00:00:00.000Z'),
('seed-dubai-8','printer-rental-dubai','Do you serve free zones like JAFZA, DMCC, and DIFC?','Yes. We regularly supply and service rental printers in JAFZA, DMCC (JLT), DIFC, Dubai Internet City, Dubai Media City, Dubai Silicon Oasis, and DAFZA. Billing can be arranged in AED or USD for free zone entities.',8,1,'2026-01-01T00:00:00.000Z'),
('seed-dubai-9','printer-rental-dubai','Can I upgrade my rented printer during the contract in Dubai?','Absolutely. Our ''Growth Guard'' policy allows you to upgrade your printer or photocopier at any point during the rental contract — scaling from a small desktop unit to a high-volume A3 copier as your business grows. No termination fees apply for upgrades.',9,1,'2026-01-01T00:00:00.000Z'),
('seed-dubai-10','printer-rental-dubai','What happens to the printer at the end of the Dubai rental contract?','At the end of the rental term, we collect the equipment at no charge. You can renew, upgrade to newer equipment, or simply return the machine. There are no exit fees and no disposal costs — Sahara handles the full lifecycle of every machine we rent.',10,1,'2026-01-01T00:00:00.000Z');

-- Printer Rental Abu Dhabi
INSERT OR IGNORE INTO faqs (id, pageSlug, question, answer, sortOrder, isActive, createdAt) VALUES
('seed-auh-1','printer-rental-abu-dhabi','How much does printer rental cost in Abu Dhabi?','Printer rental in Abu Dhabi starts from AED 250/month for an A4 desktop model. A3 multifunction photocopiers for shared offices range from AED 500-900/month. High-volume enterprise devices start at AED 1,000/month. All plans include zero deposit, free OEM toner, free delivery, and weekly preventive maintenance.',1,1,'2026-01-01T00:00:00.000Z'),
('seed-auh-2','printer-rental-abu-dhabi','What is the response time for Abu Dhabi printer repair?','We schedule weekly preventive maintenance visits for all Abu Dhabi rental units. For emergency breakdowns, we dispatch a technician within 4-6 hours to anywhere in Abu Dhabi — including Mussafah, Khalifa City, Al Reem Island, and Yas Island. Same-day replacement units are available if the repair takes longer.',2,1,'2026-01-01T00:00:00.000Z'),
('seed-auh-3','printer-rental-abu-dhabi','Do I need a deposit for printer rental in Abu Dhabi?','No deposit required. Sahara''s Abu Dhabi printer rental plans are all zero-deposit. You only pay your first month to start. This is particularly valuable for businesses in Abu Dhabi''s ADGM and free zones where capital preservation is a priority.',3,1,'2026-01-01T00:00:00.000Z'),
('seed-auh-4','printer-rental-abu-dhabi','Which printer brands do you rent in Abu Dhabi?','We rent Canon imageRUNNER ADVANCE, Kyocera TASKalfa, HP LaserJet Enterprise, Xerox WorkCentre, and Ricoh MP series in Abu Dhabi. Canon and Kyocera are most popular among Mussafah industrial clients and Al Reem Island offices.',4,1,'2026-01-01T00:00:00.000Z'),
('seed-auh-5','printer-rental-abu-dhabi','Is toner included in the Abu Dhabi rental plan?','Yes. All Abu Dhabi printer rental plans include genuine Canon or Kyocera OEM toner at no extra cost. We proactively monitor toner levels remotely and deliver replacements before you run out — typically within 24 hours of detection.',5,1,'2026-01-01T00:00:00.000Z'),
('seed-auh-6','printer-rental-abu-dhabi','Do you serve Mussafah Industrial Area and free zones?','Yes. Mussafah is one of our primary Abu Dhabi service zones. We also serve KEZAD (Khalifa Economic Zones), Abu Dhabi Global Market (ADGM), twofour54, and all Abu Dhabi free zones.',6,1,'2026-01-01T00:00:00.000Z'),
('seed-auh-7','printer-rental-abu-dhabi','How long are your Abu Dhabi printer rental contracts?','Contracts are offered for 12, 24, or 36 months. Shorter rentals from 1-6 months are available for project offices, exhibitions at ADNEC, and seasonal setups. Longer contracts have lower monthly rates. All contracts include upgrade rights.',7,1,'2026-01-01T00:00:00.000Z'),
('seed-auh-8','printer-rental-abu-dhabi','Can I upgrade my printer during the Abu Dhabi rental contract?','Yes. Upgrade to a higher-speed or colour model at any point during your Abu Dhabi contract without penalty. This is useful for Abu Dhabi businesses that grow quickly — especially in sectors like real estate, construction, and government contracting.',8,1,'2026-01-01T00:00:00.000Z');

-- Photocopier Rental Sharjah
INSERT OR IGNORE INTO faqs (id, pageSlug, question, answer, sortOrder, isActive, createdAt) VALUES
('seed-shj-1','photocopier-rental-sharjah','How much does photocopier rental cost in Sharjah?','Photocopier rental in Sharjah starts from AED 250/month for an A4 desktop copier. A3 multifunction devices for shared offices range from AED 500-900/month. Enterprise high-volume copiers start at AED 1,000/month. All plans include zero deposit, free toner, free delivery, and on-site support.',1,1,'2026-01-01T00:00:00.000Z'),
('seed-shj-2','photocopier-rental-sharjah','What is your emergency response time in Sharjah?','We guarantee a 60-minute on-site response time for emergency breakdowns across Sharjah, including SAIF Zone, Industrial Area, Al Majaz, and Muweilah. Our Sharjah-based technicians are dispatched immediately upon your call to +971 50 382 3969.',2,1,'2026-01-01T00:00:00.000Z'),
('seed-shj-3','photocopier-rental-sharjah','Do I need to pay a deposit for photocopier rental in Sharjah?','No deposit required. Sahara offers zero-deposit photocopier rental across all Sharjah plans. You only pay your first month''s rental to get started.',3,1,'2026-01-01T00:00:00.000Z'),
('seed-shj-4','photocopier-rental-sharjah','Which photocopier brands do you rent in Sharjah?','We rent Canon imageRUNNER ADVANCE, Kyocera TASKalfa, Xerox WorkCentre, HP LaserJet, and Ricoh MP series in Sharjah. Canon and Kyocera are our most popular devices for Sharjah Industrial Area businesses and SAIF Zone companies.',4,1,'2026-01-01T00:00:00.000Z'),
('seed-shj-5','photocopier-rental-sharjah','Is toner included in the Sharjah rental plan?','Yes. All our Sharjah photocopier rental plans include genuine OEM toner at no extra charge. You never need to buy or order toner separately — we monitor usage and deliver proactively before you run out.',5,1,'2026-01-01T00:00:00.000Z'),
('seed-shj-6','photocopier-rental-sharjah','Can SAIF Zone companies rent copiers from Sahara?','Absolutely. We serve all SAIF Zone (Sharjah Airport International Free Zone) businesses with the same zero-deposit, free-toner plans. Invoicing can be in UAE dirham or US dollar as required.',6,1,'2026-01-01T00:00:00.000Z'),
('seed-shj-7','photocopier-rental-sharjah','How long are your Sharjah photocopier rental contracts?','Contracts are available for 12, 24, or 36 months. Shorter-term rentals (1-6 months) are available for exhibitions, project offices, and seasonal business peaks. Longer contracts attract lower monthly rates.',7,1,'2026-01-01T00:00:00.000Z'),
('seed-shj-8','photocopier-rental-sharjah','Do you service Sharjah Industrial Area specifically?','Sharjah Industrial Area (Areas 1-18) is one of our highest-density service zones. We have dedicated technicians for Industrial Area and can reach any location there in under 45 minutes.',8,1,'2026-01-01T00:00:00.000Z');

-- Printer Rental Fujairah
INSERT OR IGNORE INTO faqs (id, pageSlug, question, answer, sortOrder, isActive, createdAt) VALUES
('seed-fjr-1','printer-rental-fujairah','How much does printer rental cost in Fujairah?','Printer rental in Fujairah starts from AED 250/month for an A4 desktop model. A3 multifunction photocopiers range from AED 500-900/month. Enterprise high-volume devices start at AED 1,000/month. All Fujairah plans include zero deposit, free toner, free delivery, and on-site support.',1,1,'2026-01-01T00:00:00.000Z'),
('seed-fjr-2','printer-rental-fujairah','What is your response time for Fujairah clients?','We provide weekly scheduled service visits for Fujairah rental clients. For emergency breakdowns, we dispatch a technician within 4-6 hours to Fujairah City, Dibba, Kalba, and the Fujairah Free Trade Zone.',2,1,'2026-01-01T00:00:00.000Z'),
('seed-fjr-3','printer-rental-fujairah','Do you serve the Fujairah Free Trade Zone?','Yes. Fujairah Free Trade Zone (FFTZ) clients are served with the same zero-deposit, free-toner plans. We handle free zone documentation for equipment leases and can invoice in USD or AED as preferred.',3,1,'2026-01-01T00:00:00.000Z'),
('seed-fjr-4','printer-rental-fujairah','Is there a deposit for printer rental in Fujairah?','No deposit required. All Fujairah printer rental plans are zero-deposit. You only pay your first month to start — ideal for new businesses in Fujairah''s growing industrial and free zone sectors.',4,1,'2026-01-01T00:00:00.000Z'),
('seed-fjr-5','printer-rental-fujairah','Which brands do you rent in Fujairah?','We rent Canon imageRUNNER ADVANCE, Kyocera TASKalfa, HP LaserJet Enterprise, and Xerox WorkCentre in Fujairah. Canon and Kyocera are the most popular for Fujairah Port area businesses and oil storage companies.',5,1,'2026-01-01T00:00:00.000Z'),
('seed-fjr-6','printer-rental-fujairah','Is toner included in the Fujairah rental plan?','Yes. All Fujairah plans include unlimited genuine Canon or Kyocera OEM toner at no extra charge. We monitor toner remotely and deliver replacements proactively.',6,1,'2026-01-01T00:00:00.000Z'),
('seed-fjr-7','printer-rental-fujairah','Do you serve Dibba and Kalba?','Yes. Dibba Al Fujairah and Kalba are within our regular Fujairah service coverage. These East Coast areas receive weekly scheduled maintenance and are included in our emergency response coverage.',7,1,'2026-01-01T00:00:00.000Z'),
('seed-fjr-8','printer-rental-fujairah','How long are your Fujairah rental contracts?','Contracts are available for 12, 24, or 36 months. Short-term 1-6 month rentals are available for construction site offices, temporary events, and seasonal businesses near Fujairah Port.',8,1,'2026-01-01T00:00:00.000Z');

-- Printer Rental RAK
INSERT OR IGNORE INTO faqs (id, pageSlug, question, answer, sortOrder, isActive, createdAt) VALUES
('seed-rak-1','printer-rental-rak','What is your response time in Ras Al Khaimah?','We provide next-business-day service visits for RAK clients. Emergency breakdown response is within 4-6 hours across Ras Al Khaimah City, Al Hamra, RAK Free Trade Zone, and Al Marjan Island. If we cannot repair same-day, a replacement unit is delivered.',1,1,'2026-01-01T00:00:00.000Z'),
('seed-rak-2','printer-rental-rak','Do you serve RAK Free Trade Zone businesses?','Yes. RAK FTZ is a key service area. We handle all free zone documentation for equipment lease agreements, and can invoice in USD or AED as required by RAK FTZ companies.',2,1,'2026-01-01T00:00:00.000Z'),
('seed-rak-3','printer-rental-rak','Is there a deposit for printer rental in RAK?','No deposit. All RAK printer rental plans are zero-deposit — pay only your first month''s rental to start. This makes it easy for new RAK Free Zone setups and growing businesses.',3,1,'2026-01-01T00:00:00.000Z'),
('seed-rak-4','printer-rental-rak','Which brands do you rent in Ras Al Khaimah?','We rent Canon imageRUNNER ADVANCE, Kyocera TASKalfa, HP LaserJet Enterprise, and Xerox WorkCentre in RAK. Canon and Kyocera are the most popular choices for RAK''s manufacturing and hospitality sectors.',4,1,'2026-01-01T00:00:00.000Z'),
('seed-rak-5','printer-rental-rak','Is toner included in the RAK rental plan?','Yes. All RAK plans include unlimited genuine Canon or Kyocera OEM toner. We monitor toner levels remotely and deliver proactively before you run out.',5,1,'2026-01-01T00:00:00.000Z'),
('seed-rak-6','printer-rental-rak','How long are your RAK rental contracts?','Contracts are available for 12, 24, or 36 months. Short-term 1-6 month rentals are available for events, construction site offices, and seasonal business spikes. Longer contracts attract lower monthly rates.',6,1,'2026-01-01T00:00:00.000Z'),
('seed-rak-7','printer-rental-rak','Do you provide network setup in Ras Al Khaimah?','Yes. Free network and Wi-Fi configuration is included with all RAK installations. Our technician connects the printer to your network, sets up scan-to-email, and configures mobile printing (AirPrint/Mopria) — all at no extra charge.',7,1,'2026-01-01T00:00:00.000Z'),
('seed-rak-8','printer-rental-rak','Can I upgrade my printer during the RAK contract?','Yes. You can upgrade to a higher-capacity model at any time during your RAK rental contract without penalty. This is common for RAK FTZ businesses that grow from 1 to multiple office locations.',8,1,'2026-01-01T00:00:00.000Z');

-- Printer Rental Al Ain
INSERT OR IGNORE INTO faqs (id, pageSlug, question, answer, sortOrder, isActive, createdAt) VALUES
('seed-aln-1','printer-rental-al-ain','How much does printer rental cost in Al Ain?','Printer rental in Al Ain starts from AED 250/month for an A4 desktop model. A3 multifunction photocopiers range from AED 500-900/month. Enterprise high-volume devices start at AED 1,000/month. All Al Ain plans include zero deposit, free OEM toner, free delivery, and on-site support.',1,1,'2026-01-01T00:00:00.000Z'),
('seed-aln-2','printer-rental-al-ain','What is the response time for printer support in Al Ain?','We schedule weekly preventive maintenance visits for Al Ain rental clients. For emergency breakdowns, a technician is dispatched within 4-6 hours to Al Ain Central, Al Jimi, Al Khubaisi, Al Murabba, and the Al Ain Industrial Area.',2,1,'2026-01-01T00:00:00.000Z'),
('seed-aln-3','printer-rental-al-ain','Do I need a deposit for printer rental in Al Ain?','No deposit required. All Al Ain printer rental plans are zero-deposit. You only pay the first month''s rental to start — suitable for educational institutions, healthcare facilities, and SMEs in Al Ain''s growing business districts.',3,1,'2026-01-01T00:00:00.000Z'),
('seed-aln-4','printer-rental-al-ain','Which printer brands do you rent in Al Ain?','We rent Canon imageRUNNER ADVANCE, Kyocera TASKalfa, HP LaserJet Enterprise, and Xerox WorkCentre in Al Ain. Canon and Kyocera are the most popular choices for Al Ain''s healthcare, education, and government sectors.',4,1,'2026-01-01T00:00:00.000Z'),
('seed-aln-5','printer-rental-al-ain','Is toner included in the Al Ain rental plan?','Yes. All Al Ain plans include unlimited genuine Canon or Kyocera OEM toner at no extra charge. Toner levels are monitored remotely and replacements are delivered proactively.',5,1,'2026-01-01T00:00:00.000Z'),
('seed-aln-6','printer-rental-al-ain','Do you serve Al Ain University area and educational institutions?','Yes. Al Ain University, UAE University, HCT Al Ain, and other educational institutions are within our service coverage. We provide high-volume enterprise copiers with user quota management and cost-per-department reporting suitable for campus environments.',6,1,'2026-01-01T00:00:00.000Z'),
('seed-aln-7','printer-rental-al-ain','What happens if my printer breaks down in Al Ain?','Call +971 50 382 3969 and we dispatch a technician within 4-6 hours to anywhere in Al Ain. If we cannot repair it same-day, we deliver a replacement unit at no extra charge so your operations continue without interruption.',7,1,'2026-01-01T00:00:00.000Z'),
('seed-aln-8','printer-rental-al-ain','Do you serve the Al Ain Industrial Area?','Yes. Al Ain Industrial Area is within our regular service coverage. Manufacturing, food processing, and construction businesses in the industrial zone use our enterprise copiers for production documentation, with weekly preventive maintenance included.',8,1,'2026-01-01T00:00:00.000Z');

-- Services: Printer Rental
INSERT OR IGNORE INTO faqs (id, pageSlug, question, answer, sortOrder, isActive, createdAt) VALUES
('seed-spr-1','services/printer-rental','What is the minimum rental duration?','We offer flexible rental periods starting from 3 months to 36 months. Short-term rentals are available for events and temporary needs.',1,1,'2026-01-01T00:00:00.000Z'),
('seed-spr-2','services/printer-rental','Is maintenance included in the rental?','Yes, all our rental plans include comprehensive maintenance coverage. Our technicians perform regular servicing and emergency repairs at no additional cost.',2,1,'2026-01-01T00:00:00.000Z'),
('seed-spr-3','services/printer-rental','Can I upgrade my rented printer?','Absolutely! Our ''Growth Guard'' policy allows you to upgrade your equipment anytime during the contract based on your business needs.',3,1,'2026-01-01T00:00:00.000Z'),
('seed-spr-4','services/printer-rental','What brands do you offer for rental?','We offer all major brands including HP, Canon, Brother, Ricoh, Xerox, Sharp, Kyocera, and Epson. Our fleet includes enterprise, mid-range, and budget options.',4,1,'2026-01-01T00:00:00.000Z'),
('seed-spr-5','services/printer-rental','Do you require a deposit?','We offer zero deposit options for qualified businesses. Contact us to learn more about our deposit-free plans.',5,1,'2026-01-01T00:00:00.000Z'),
('seed-spr-6','services/printer-rental','What happens if the printer breaks down?','All rentals include full maintenance and repair coverage. We aim for 4-hour emergency response for critical issues.',6,1,'2026-01-01T00:00:00.000Z'),
('seed-spr-7','services/printer-rental','Can I cancel my rental contract?','Yes, we offer flexible terms with no exit fees. You can return or upgrade equipment at any time.',7,1,'2026-01-01T00:00:00.000Z'),
('seed-spr-8','services/printer-rental','Is toner included in the rental price?','Yes! All our rental plans include unlimited genuine toner. No hidden costs for consumables.',8,1,'2026-01-01T00:00:00.000Z'),
('seed-spr-9','services/printer-rental','Do you offer short-term rentals?','Yes, we offer short-term rentals for events, conferences, and temporary office needs. Contact us for daily and weekly rates.',9,1,'2026-01-01T00:00:00.000Z'),
('seed-spr-10','services/printer-rental','What areas do you serve?','We serve all across UAE including Dubai, Sharjah, Abu Dhabi, Ajman, RAK, Fujairah, and Al Ain.',10,1,'2026-01-01T00:00:00.000Z');

-- Services: Photocopier Rental
INSERT OR IGNORE INTO faqs (id, pageSlug, question, answer, sortOrder, isActive, createdAt) VALUES
('seed-scr-1','services/photocopier-rental','What is the difference between photocopier rental and printer rental?','A photocopier (multifunction device / MFP) combines high-volume copying, printing, scanning, and faxing in a single A3-capable device — designed for shared office use by 10-50+ people. A desktop printer is typically A4-only and serves 1-5 users. Photocopiers process thousands of pages daily at a lower cost-per-page than desktop printers.',1,1,'2026-01-01T00:00:00.000Z'),
('seed-scr-2','services/photocopier-rental','How much does photocopier rental cost in UAE?','Photocopier rental in UAE starts from AED 500/month for a monochrome A3 multifunction device. Color A3 photocopiers start from AED 700/month. Enterprise high-speed devices (60+ ppm) range from AED 1,200-2,000/month. All plans include zero deposit, unlimited OEM toner, maintenance, and repairs.',2,1,'2026-01-01T00:00:00.000Z'),
('seed-scr-3','services/photocopier-rental','Which photocopier brands do you rent in Dubai and Sharjah?','Sahara rents Canon imageRUNNER ADVANCE (C5540i, C5250, 4551i) and Kyocera TASKalfa (2553ci, 3553ci, 5053ci) as primary lines. We also rent Ricoh MP C3004, Xerox AltaLink C8055, and Sharp MX-4071 on request.',3,1,'2026-01-01T00:00:00.000Z'),
('seed-scr-4','services/photocopier-rental','Is toner included in the photocopier rental?','Yes — all Sahara photocopier rental plans include unlimited genuine OEM toner at no additional charge. We pro-actively monitor toner levels remotely and replenish before you run out.',4,1,'2026-01-01T00:00:00.000Z'),
('seed-scr-5','services/photocopier-rental','How long is the minimum rental period for a photocopier?','Standard photocopier rental contracts run 12-36 months. For events, exhibitions, or temporary office setups, we offer short-term rentals from 1 day to 3 months.',5,1,'2026-01-01T00:00:00.000Z'),
('seed-scr-6','services/photocopier-rental','Can the rented photocopier connect to our office network and email?','Yes. Our engineers configure full network integration including LAN/Wi-Fi connectivity, scan-to-email, scan-to-folder, cloud integration (Google Drive, OneDrive, SharePoint), and user authentication. Setup is included at no additional charge.',6,1,'2026-01-01T00:00:00.000Z'),
('seed-scr-7','services/photocopier-rental','What happens if the photocopier breaks down?','All rental photocopiers are covered by our full service agreement. We target a 4-hour on-site response for Dubai and Sharjah. If a repair cannot be completed within 24 hours, we deliver a loaner machine at no cost.',7,1,'2026-01-01T00:00:00.000Z');

-- Services: AMC
INSERT OR IGNORE INTO faqs (id, pageSlug, question, answer, sortOrder, isActive, createdAt) VALUES
('seed-amc-1','services/amc','What is an Annual Maintenance Contract (AMC) for printers in UAE?','A Printer Annual Maintenance Contract (AMC) is a service agreement where Sahara''s certified technicians perform scheduled preventive maintenance visits on your office printers and photocopiers throughout the year. It includes regular servicing, cleaning, calibration, and priority emergency response — at a fixed monthly or annual fee.',1,1,'2026-01-01T00:00:00.000Z'),
('seed-amc-2','services/amc','How is a Printer AMC different from a rental plan?','With a printer rental from Sahara, you pay a monthly fee that includes the machine, toner, maintenance, and repairs — you never own the equipment. A Printer AMC is for equipment you already own: you pay a service contract fee covering maintenance and repairs, but continue owning the machine.',2,1,'2026-01-01T00:00:00.000Z'),
('seed-amc-3','services/amc','What does the Sahara Professional AMC plan include?','The Professional AMC plan (AED 499/month per machine) includes: monthly preventive maintenance visits, all OEM replacement parts at no extra cost, 24/7 emergency support, a loaner device if repair exceeds 24 hours, priority scheduling, and a quarterly performance report for your fleet.',3,1,'2026-01-01T00:00:00.000Z'),
('seed-amc-4','services/amc','How many printers can be covered under one AMC contract?','There is no minimum or maximum. Sahara covers single machines and multi-site enterprise fleets of 100+ devices under consolidated AMC contracts. Multi-machine contracts receive volume pricing discounts.',4,1,'2026-01-01T00:00:00.000Z'),
('seed-amc-5','services/amc','Is toner included in the printer AMC?','Toner is not included in the Basic AMC plan but is included in our printer rental plans. The Professional and Enterprise AMC plans can be upgraded to include toner supply at an additional per-page or monthly rate.',5,1,'2026-01-01T00:00:00.000Z'),
('seed-amc-6','services/amc','Do you offer AMC for all printer brands?','Yes. Sahara''s AMC covers all major printer and photocopier brands: Canon, HP, Kyocera, Ricoh, Xerox, Brother, Sharp, Epson, Konica Minolta, and Toshiba. Our technicians hold brand-specific certifications for Canon and Kyocera, and are authorized service partners for HP and Xerox.',6,1,'2026-01-01T00:00:00.000Z');

-- Services: Repair
INSERT OR IGNORE INTO faqs (id, pageSlug, question, answer, sortOrder, isActive, createdAt) VALUES
('seed-rep-1','services/repair','How quickly can a printer repair technician reach my office in Dubai?','For Dubai and Sharjah locations, our average response time is 4 hours for standard service and under 2 hours for emergency callouts. Abu Dhabi locations typically receive same-day service. We dispatch technicians from the nearest service hub to minimize travel time.',1,1,'2026-01-01T00:00:00.000Z'),
('seed-rep-2','services/repair','Do you use original OEM parts for printer repairs?','Yes — exclusively. Sahara only installs genuine OEM (Original Equipment Manufacturer) replacement parts for all brands including Canon, HP, Kyocera, Ricoh, and Xerox. We do not use compatible or third-party parts, which preserves your warranty and ensures long-term performance.',2,1,'2026-01-01T00:00:00.000Z'),
('seed-rep-3','services/repair','Which printer brands do you repair in UAE?','Our certified technicians repair all major printer and photocopier brands: Canon, HP, Kyocera, Ricoh, Xerox, Brother, Sharp, Epson, Konica Minolta, and Toshiba. We carry mobile parts inventory for the most common models.',3,1,'2026-01-01T00:00:00.000Z'),
('seed-rep-4','services/repair','What is the cost of printer repair service in Dubai?','Repair costs vary depending on the fault and parts required. We provide a transparent, itemized quote before any work begins — no surprise charges. Clients on our AMC or printer rental plans receive repairs at no additional cost.',4,1,'2026-01-01T00:00:00.000Z'),
('seed-rep-5','services/repair','Do you offer emergency printer repair service on weekends?','Yes. We operate Saturday through Thursday, 8:00 AM – 8:00 PM, with 24/7 emergency support for critical failures. For rental clients and AMC contract holders, emergency response is guaranteed around the clock.',5,1,'2026-01-01T00:00:00.000Z'),
('seed-rep-6','services/repair','What warranty do you provide on printer repairs?','All repair work carries a 30-day workmanship warranty. If the same fault recurs within 30 days of a completed repair, we return and fix it at no additional charge. OEM parts carry the manufacturer''s standard warranty.',6,1,'2026-01-01T00:00:00.000Z');
