-- Migration 018: AEO Q&A seed for the answer-engine rollout
--
-- Adds 3-5 new FAQ rows per page on top of the existing 005/012/014 seeds.
-- Every answer follows the AEO format contract documented in
-- docs/seo/qa-corpus-2026-08.md:
--   * first sentence answers directly in under 15 words
--   * whole answer is 40-60 words and stands alone as an AI search snippet
--     (no "as mentioned above", no pronouns pointing at page context)
--   * supportingPoints is a JSON string array of concrete facts, surfaced by
--     src/lib/faqs.ts -> FaqItem.supportingPoints (column added in 017)
--
-- Questions are sourced, not invented: GSC query data for
-- sc-domain:saharaprinter.com (2026-05-15 -> 2026-08-13), PAA harvesting, and
-- a competitor question inventory. See the corpus doc for provenance per row.
--
-- pageSlug values reuse the exact strings already in the codebase (012 and 005)
-- so getFaqsForPage() picks them up with no call-site changes:
--   services/printer-rental, services/photocopier-rental, services/repair,
--   services/amc, printer-rental-dubai, printer-rental-abu-dhabi,
--   photocopier-rental-sharjah, printer-rental-al-ain, printer-rental-fujairah,
--   printer-rental-rak, papercut-print-management
-- plus one new slug following the same services/ convention:
--   services/paper-shredder-rental
--
-- sortOrder starts at 100 so these land after the existing seeded rows.
-- INSERT OR IGNORE keeps admin-entered edits and re-runs safe.

-- ── Services: Printer Rental (angle: what a rental plan includes) ──
INSERT OR IGNORE INTO faqs (id, pageSlug, question, answer, sortOrder, isActive, createdAt, supportingPoints) VALUES
('qa-spr-1','services/printer-rental','What is included in a printer rental plan in the UAE?','Every Sahara rental plan includes the machine, toner, maintenance, and repairs. One fixed monthly fee from AED 250 covers unlimited genuine OEM toner, scheduled preventive servicing, all parts and labour, and free delivery with network setup. There is no deposit, no metered page charge, and no exit fee.',100,1,'2026-08-13T00:00:00.000Z','["A4 desktop from AED 250/month; A3 mid-range AED 500-800; A3 enterprise AED 1,000-2,000","Contracts run 3 to 36 months, with mid-contract upgrades at no penalty","Unlimited genuine OEM toner is monitored and replenished proactively","4-hour emergency response target across all seven emirates"]'),
('qa-spr-2','services/printer-rental','Which printer brands can I rent in the UAE?','Sahara rents Canon, Kyocera, HP, Ricoh, Xerox, Brother, Sharp, and Epson equipment. All brands come under identical terms: zero deposit, unlimited OEM toner, and full maintenance included in one monthly fee. Canon and Kyocera are the most requested in the UAE for their reliability in high-heat office conditions.',101,1,'2026-08-13T00:00:00.000Z','["Canon imageRUNNER ADVANCE and Kyocera TASKalfa are the highest-volume rented ranges","Brand choice does not change the monthly terms, deposit, or toner inclusion","HP LaserJet Enterprise, Ricoh MP and Xerox AltaLink also available","Mixed-brand fleets supported under a single consolidated contract"]'),
('qa-spr-3','services/printer-rental','Who pays for repairs on a rented printer?','Sahara pays. Repairs, spare parts, and labour are covered by the monthly rental fee, with no per-callout charge and no cap on the number of visits. If a fault cannot be fixed within 24 hours, a replacement machine is delivered free so printing continues uninterrupted.',102,1,'2026-08-13T00:00:00.000Z','["No callout fee, no parts bill, and no limit on the number of service visits","Free loaner machine if a repair runs beyond 24 hours","Factory-certified technicians using genuine OEM parts only","4-hour emergency response target; 60 minutes in Sharjah"]'),
('qa-spr-4','services/printer-rental','Can I change to a bigger printer partway through a rental contract?','Yes. Sahara''s Growth Guard policy allows equipment upgrades at any point mid-contract. A small A4 desktop unit can be swapped for a high-volume A3 multifunction copier as headcount or print volume rises, with no termination penalty and no re-contracting fee. The monthly rate adjusts to the new tier.',103,1,'2026-08-13T00:00:00.000Z','["Upgrades allowed at any point in the term with no termination penalty","Monthly rate moves to the new device tier; nothing else in the contract changes","Downgrades also possible if print volume falls","Additional units can be added to an existing contract at fleet rates"]');

-- ── Services: Photocopier Rental (angle: A3 multifunction specifics) ──
INSERT OR IGNORE INTO faqs (id, pageSlug, question, answer, sortOrder, isActive, createdAt, supportingPoints) VALUES
('qa-pcr-1','services/photocopier-rental','What is A3 photocopier rental and how does it differ from A4?','A3 photocopier rental covers machines printing sheets twice the size of A4. These multifunction devices print, copy, scan, and fax from one shared unit, handle far higher monthly volumes than a desktop A4 printer, and rent from AED 500 per month with toner, maintenance, and network setup included.',100,1,'2026-08-13T00:00:00.000Z','["An A3 sheet is 297 x 420 mm - exactly double A4","A3 machines also print A4, replacing several separate desktop printers","Canon imageRUNNER ADVANCE and Kyocera TASKalfa are the most-rented A3 ranges","From AED 500/month with zero deposit and unlimited genuine OEM toner"]'),
('qa-pcr-2','services/photocopier-rental','How much does a copier on rent cost per month in the UAE?','Copier rental in the UAE runs from AED 500 to AED 2,000 per month. A3 mid-range multifunction copiers suited to 10-30 users sit at AED 500-800; high-volume enterprise copiers for large offices run AED 1,000-2,000. Every tier includes toner, maintenance, parts, and delivery at no extra cost.',101,1,'2026-08-13T00:00:00.000Z','["A3 mid-range AED 500-800/month for offices of 10-30 users","A3 enterprise AED 1,000-2,000/month for high-volume departments","Fleet discounts apply automatically from three machines upward","No deposit, no per-page metering, no exit fee at any tier"]'),
('qa-pcr-3','services/photocopier-rental','Is toner included when you rent a photocopier in the UAE?','Yes. Unlimited genuine OEM toner is included in every Sahara copier rental plan. Toner levels are monitored remotely and cartridges are delivered before a machine runs out, so no one in the office orders or stocks consumables. Only paper is billed separately from the monthly fee.',102,1,'2026-08-13T00:00:00.000Z','["Genuine OEM toner only - no compatible or refilled cartridges","Levels monitored remotely, replenished proactively before depletion","Drums, fusers and developers are also covered by the rental fee","Paper is the only consumable the customer supplies"]'),
('qa-pcr-4','services/photocopier-rental','Can one photocopier serve an office that also needs scanning and faxing?','Yes. Most Sahara rental copiers are multifunction devices covering print, copy, scan, and fax in one unit. Scan-to-email, scan-to-folder, and scan-to-cloud are configured during installation. A single A3 multifunction copier typically replaces a desktop printer, a scanner, and a standalone fax machine.',103,1,'2026-08-13T00:00:00.000Z','["Print, copy, scan and fax from one networked device","Scan-to-email, scan-to-folder and scan-to-cloud configured at installation","Network setup and driver rollout included in the delivery visit","PaperCut integration available for per-user and per-department tracking"]');

-- ── Services: Repair (angle: cost, and what a callout buys) ──
INSERT OR IGNORE INTO faqs (id, pageSlug, question, answer, sortOrder, isActive, createdAt, supportingPoints) VALUES
('qa-rep-1','services/repair','How much does it cost to repair a printer in the UAE?','Printer repair in the UAE starts from AED 150 per callout. That fee covers an on-site visit by a factory-certified technician, full diagnosis, and labour; genuine OEM parts are quoted separately before any work begins. Every repair carries a 30-day workmanship warranty. Machines under a Sahara AMC pay nothing per callout.',100,1,'2026-08-13T00:00:00.000Z','["From AED 150 per callout, covering visit, diagnosis and labour","Parts quoted for approval before work starts - no surprise invoices","30-day workmanship warranty on every repair","Free of charge for machines under an AMC plan"]'),
('qa-rep-2','services/repair','Which printer brands does Sahara repair?','Sahara repairs Canon, HP, Kyocera, Ricoh, Xerox, Brother, Sharp, and Epson devices. Coverage spans desktop printers, A3 multifunction copiers, and wide-format plotters, including units bought elsewhere and machines out of manufacturer warranty. Technicians carry factory certification and fit genuine OEM parts only.',101,1,'2026-08-13T00:00:00.000Z','["Desktop printers, A3 multifunction copiers, and wide-format plotters all serviced","Machines purchased from other suppliers are accepted","Out-of-warranty units repaired at the same rates","Genuine OEM parts only - no compatible substitutes"]'),
('qa-rep-3','services/repair','Do I have to bring the printer in, or does a technician come to the office?','A technician comes to your office. On-site repair is the default across Dubai, Sharjah, Abu Dhabi, Ajman, RAK, Fujairah, and Al Ain, so machines stay on the network and no one carries hardware across the emirates. Workshop repair is used only when a fault needs bench-level component work.',102,1,'2026-08-13T00:00:00.000Z','["On-site repair is standard in all seven emirates","Most faults are resolved in a single visit without removing the machine","Workshop collection arranged free of charge when bench work is required","Loaner machine supplied if a workshop repair exceeds 24 hours"]'),
('qa-rep-4','services/repair','How long does a typical printer repair take?','Most printer repairs are completed within a single on-site visit. Common faults such as paper jams, roller wear, fuser errors, and print-quality defects are fixed the same day from parts carried in the van. Repairs needing an ordered component are scheduled once the part arrives, usually within two working days.',103,1,'2026-08-13T00:00:00.000Z','["Jams, roller wear, fuser faults and quality defects fixed on the first visit","Common consumable-life parts carried on the service vehicle","Ordered parts typically arrive within two working days","Loaner machine available if downtime would exceed 24 hours"]');

-- ── Services: AMC (angle: inclusions AND exclusions - the gap every competitor fills) ──
INSERT OR IGNORE INTO faqs (id, pageSlug, question, answer, sortOrder, isActive, createdAt, supportingPoints) VALUES
('qa-amc-1','services/amc','What does a printer AMC cover, and what is excluded?','A printer AMC covers preventive servicing, labour, and priority emergency callouts. Sahara''s plans start from AED 299 per month per machine and include scheduled visits, unlimited breakdown calls, and OEM spare parts. Consumables such as toner, ink, and paper are billed separately, as is damage from misuse or power surges.',100,1,'2026-08-13T00:00:00.000Z','["Included: scheduled preventive visits, unlimited breakdown calls, labour, OEM spare parts","Excluded: toner, ink, paper, and damage from misuse, power surges or unauthorised servicing","From AED 299/month per machine","4-hour emergency response target across all seven emirates"]'),
('qa-amc-2','services/amc','How often does an engineer visit under a printer AMC?','Scheduled preventive visits happen quarterly on most Sahara AMC plans. High-volume machines move to a bi-monthly or monthly cadence depending on page counts. Emergency breakdown calls are unlimited and sit outside that schedule, targeting a 4-hour response. Every visit is logged so service history follows the machine.',101,1,'2026-08-13T00:00:00.000Z','["Quarterly preventive visits as standard; more frequent for high-volume machines","Emergency callouts are unlimited and do not consume the scheduled visit allowance","Each visit logged against the machine for warranty and audit purposes","Multi-site fleets scheduled together to minimise office disruption"]'),
('qa-amc-3','services/amc','Is an AMC cheaper than paying for printer repairs individually?','For most UAE offices, yes, once two or more callouts a year are likely. Break-fix repair starts at AED 150 per visit plus parts, which are unpredictable. An AMC from AED 299 per month fixes that cost, covers OEM parts, and adds priority dispatch ahead of non-contract customers.',102,1,'2026-08-13T00:00:00.000Z','["Break-fix: from AED 150 per callout plus parts quoted case by case","AMC: fixed monthly fee covering labour, parts and unlimited callouts","AMC holders get priority dispatch ahead of non-contract jobs","Rented machines already include AMC-equivalent cover at no extra charge"]'),
('qa-amc-4','services/amc','Can Sahara cover printers bought from another supplier under an AMC?','Yes. Sahara AMC plans cover machines purchased anywhere, including out-of-warranty units and mixed-brand fleets. An initial inspection establishes condition and any pre-existing faults before the contract starts. Canon, HP, Kyocera, Ricoh, Xerox, Brother, Sharp, and Epson equipment are all eligible for cover.',103,1,'2026-08-13T00:00:00.000Z','["Machines from any supplier accepted, including out-of-warranty units","Pre-contract inspection establishes condition and excludes pre-existing damage","Mixed-brand fleets covered under one consolidated contract","Multi-site plans available across Dubai, Sharjah, Abu Dhabi and the northern emirates"]');

-- ── Printer Rental Dubai (angle: delivery timing and district coverage) ──
INSERT OR IGNORE INTO faqs (id, pageSlug, question, answer, sortOrder, isActive, createdAt, supportingPoints) VALUES
('qa-dxb-1','printer-rental-dubai','How quickly can a rented printer be delivered in Dubai?','Same-day delivery is available across most Dubai districts. Business Bay, DIFC, JLT, Dubai Marina, Sheikh Zayed Road, and Deira are usually covered the same working day; everywhere else in Dubai is next-day. Sahara engineers handle network configuration on the delivery visit at no extra charge.',100,1,'2026-08-13T00:00:00.000Z','["Same-day: Business Bay, DIFC, JLT, Marina, Sheikh Zayed Road, Deira","Next-day: all remaining Dubai districts","Network setup and driver installation included in the delivery visit","Quotes issued within 2 hours of enquiry"]'),
('qa-dxb-2','printer-rental-dubai','How do I choose a printer rental company in Dubai?','Compare four things: inclusions, deposit, response time, and exit terms. What the monthly fee actually covers matters most - many Dubai quotes exclude toner or meter pages, so a low headline rate rises sharply in use. Sahara quotes one all-inclusive fee with zero deposit and no exit fee.',101,1,'2026-08-13T00:00:00.000Z','["Check whether toner, parts and labour are inside the monthly fee or billed separately","Check for per-page metering, which makes low headline rates misleading","Check the deposit - Sahara requires none for qualified businesses","Check exit terms - Sahara charges no termination or collection fee"]'),
('qa-dxb-3','printer-rental-dubai','Is there a printer rental company near my Dubai office?','Sahara serves every Dubai district from its Sharjah headquarters and Dubai service routes. Engineers cover Business Bay, DIFC, Downtown, JLT, Marina, Deira, Al Quoz, Jebel Ali, and the free zones daily, so proximity is a matter of dispatch routing rather than showroom location.',102,1,'2026-08-13T00:00:00.000Z','["Daily service routes cover all Dubai districts and free zones","HQ at Al Arabi Building, Industrial Area 11, Sharjah - roughly 30 minutes from Deira","2-hour priority dispatch for Business Bay, DIFC and Downtown Dubai","JAFZA, DMCC, DAFZA, Internet City, Media City and Silicon Oasis served directly"]'),
('qa-dxb-4','printer-rental-dubai','Can I rent a colour printer in Dubai rather than mono?','Yes. Colour A4 and A3 multifunction devices are available across the Dubai rental fleet. Colour output costs the same monthly fee tier as mono at equivalent speed and volume, because toner is unlimited and included. Colour usage can be restricted per user or department through PaperCut if budgets require it.',103,1,'2026-08-13T00:00:00.000Z','["Colour A4 and A3 multifunction devices available at standard tier pricing","Unlimited colour toner included - no per-click colour surcharge","Colour printing restrictable by user or department via PaperCut","Canon and Kyocera colour ranges most commonly deployed in Dubai"]');

-- ── Printer Rental Abu Dhabi (angle: coverage plus maintenance cadence) ──
INSERT OR IGNORE INTO faqs (id, pageSlug, question, answer, sortOrder, isActive, createdAt, supportingPoints) VALUES
('qa-auh-1','printer-rental-abu-dhabi','Which Abu Dhabi areas does Sahara cover, and how often are machines serviced?','Sahara covers all Abu Dhabi areas with weekly preventive maintenance visits. Coverage includes Mussafah, ICAD, Al Reem Island, Khalifa City, Yas Island, and the city centre, plus Al Ain. Rented machines get scheduled weekly checks rather than break-fix-only support, with a 4-to-6-hour emergency response target.',100,1,'2026-08-13T00:00:00.000Z','["Areas: Mussafah, ICAD I-III, Al Reem Island, Khalifa City, Yas Island, Corniche, Al Ain","Weekly preventive maintenance included, not charged as separate callouts","4-6 hour emergency response target for Abu Dhabi","Zero deposit, unlimited genuine OEM toner, free network setup"]'),
('qa-auh-2','printer-rental-abu-dhabi','Does Sahara rent printers to Abu Dhabi government and semi-government entities?','Yes. Sahara supplies rental fleets to Abu Dhabi government departments, semi-government entities, and their contractors, with documentation prepared for procurement and tender requirements. Contracts can be structured per department or as a single consolidated fleet agreement with itemised per-site billing.',101,1,'2026-08-13T00:00:00.000Z','["Procurement and tender documentation prepared on request","Per-department or consolidated fleet contracting available","Itemised per-site billing for multi-location entities","Audited print logs available via PaperCut integration"]'),
('qa-auh-3','printer-rental-abu-dhabi','How much does printer rental cost in Abu Dhabi?','Printer rental in Abu Dhabi starts at AED 250 per month. An A4 desktop machine sits at that entry tier; A3 multifunction copiers begin at AED 500, and high-volume enterprise units run to AED 2,000. Every tier includes zero deposit, unlimited genuine OEM toner, weekly maintenance, and free delivery.',102,1,'2026-08-13T00:00:00.000Z','["A4 desktop from AED 250/month; A3 multifunction from AED 500/month","Enterprise high-volume units to AED 2,000/month","Fleet discounts from three machines upward","Free delivery and network setup anywhere in Abu Dhabi and Al Ain"]');

-- ── Photocopier Rental Sharjah (angle: HQ proximity and 60-minute response) ──
INSERT OR IGNORE INTO faqs (id, pageSlug, question, answer, sortOrder, isActive, createdAt, supportingPoints) VALUES
('qa-shj-1','photocopier-rental-sharjah','How fast can a technician reach a Sharjah office?','Sahara targets a 60-minute on-site response anywhere in Sharjah. The company is headquartered at Al Arabi Building, Industrial Area 11, Sharjah, so engineers reach SAIF Zone, the Industrial Areas, Al Majaz, Al Nahda, and Muwaileh faster than Dubai-based providers. Photocopier rental starts from AED 250 per month.',100,1,'2026-08-13T00:00:00.000Z','["HQ at Al Arabi Building, Industrial Area 11, Sharjah - no cross-emirate travel time","Covers SAIF Zone, Industrial Areas 1-18, Al Majaz, Al Nahda, Muwaileh, Al Khan","60-minute emergency response target","Replacement machine supplied if a fix runs beyond the agreed window"]'),
('qa-shj-2','photocopier-rental-sharjah','Can a SAIF Zone company rent a photocopier from Sahara?','Yes. Sahara delivers and services rental copiers throughout SAIF Zone and Hamriyah Free Zone, with invoicing arranged to suit free-zone entity accounting. SAIF Zone sits a short drive from the Sharjah headquarters, so delivery is usually same-day and emergency response stays inside the 60-minute target.',101,1,'2026-08-13T00:00:00.000Z','["SAIF Zone and Hamriyah Free Zone served directly with same-day delivery","Free-zone entity invoicing supported alongside mainland LLC billing","60-minute emergency response maintained for free-zone addresses","Zero deposit and unlimited genuine OEM toner on all plans"]'),
('qa-shj-3','photocopier-rental-sharjah','How quickly can a photocopier be installed in Sharjah?','Same-day delivery and installation are standard across Sharjah. A copier ordered in the morning is normally networked and printing the same afternoon, including driver rollout to office machines and scan-to-email configuration. Installation, network setup, and staff walkthrough are included in the rental fee.',102,1,'2026-08-13T00:00:00.000Z','["Same-day delivery and installation standard across Sharjah","Driver rollout and scan-to-email configured during the install visit","Staff walkthrough included at no charge","Quotes issued within 2 hours of enquiry"]'),
('qa-shj-4','photocopier-rental-sharjah','Is Sahara actually based in Sharjah, or does it serve Sharjah from Dubai?','Sahara is headquartered in Sharjah, at Al Arabi Building, Industrial Area 11. That is the operating base, not a branch office, which is why the Sharjah emergency response target is 60 minutes rather than the 4 hours quoted for other emirates. The company has traded from Sharjah since 2012.',103,1,'2026-08-13T00:00:00.000Z','["Head office: Al Arabi Building, Industrial Area 11, Sharjah","Trading from Sharjah since 2012","60-minute Sharjah response target versus 4 hours elsewhere in the UAE","Spare parts and loaner machines stocked locally in Sharjah"]');

-- ── Printer Rental Al Ain (angle: sector fit) ──
INSERT OR IGNORE INTO faqs (id, pageSlug, question, answer, sortOrder, isActive, createdAt, supportingPoints) VALUES
('qa-aln-1','printer-rental-al-ain','Which Al Ain organisations rent printers from Sahara?','Healthcare, education, government, and industrial sites make up most Al Ain rentals. Clinics need reliable patient-record printing, schools and universities need per-user quota control at term-start peaks, and government offices need audited print logs. Sahara supplies Canon and Kyocera multifunction devices to all three from AED 250 monthly.',100,1,'2026-08-13T00:00:00.000Z','["Per-user quota and department cost allocation available via PaperCut","Weekly preventive maintenance covering Al Jimi, Al Muwaiji, Zakher and Al Ain Industrial Area","Audited print logs for government and compliance reporting","Canon imageRUNNER ADVANCE and Kyocera TASKalfa from AED 250/month"]'),
('qa-aln-2','printer-rental-al-ain','Does Sahara deliver rental printers to Al Ain, or only to Abu Dhabi city?','Sahara delivers to Al Ain directly. The Al Ain service route covers Al Jimi, Al Muwaiji, Zakher, Al Towayya, and Al Ain Industrial Area on a scheduled basis, so machines get the same weekly preventive maintenance as Abu Dhabi city sites rather than callout-only support.',101,1,'2026-08-13T00:00:00.000Z','["Scheduled Al Ain service route, not ad-hoc callouts from Abu Dhabi","Covers Al Jimi, Al Muwaiji, Zakher, Al Towayya, Al Ain Industrial Area","Weekly preventive maintenance included in the rental fee","Free delivery and network setup on installation"]'),
('qa-aln-3','printer-rental-al-ain','Can a school or university control student printing on a rented machine?','Yes. Sahara configures per-user and per-department print quotas through PaperCut on rented multifunction devices. Students can be given a page allowance, colour printing can be restricted or blocked entirely, and duplex can be enforced by default, which typically cuts print volume 20-30% within three months.',102,1,'2026-08-13T00:00:00.000Z','["Per-user page quotas and card or PIN release at the machine","Colour printing restrictable or blockable by user group","Duplex enforced by default to halve paper consumption","Typical volume reduction of 20-30% within three months"]');

-- ── Printer Rental Fujairah (angle: east-coast reach) ──
INSERT OR IGNORE INTO faqs (id, pageSlug, question, answer, sortOrder, isActive, createdAt, supportingPoints) VALUES
('qa-fjr-1','printer-rental-fujairah','Does Sahara deliver rental printers to Fujairah and the east coast?','Yes. Sahara delivers and services rental printers across Fujairah, reaching Fujairah City, Dibba, Kalba, Khor Fakkan, and the Fujairah Free Trade Zone. FFTZ entity billing is supported. Engineers travel from the Sharjah headquarters for scheduled maintenance and breakdowns. Rental starts at AED 250 per month with free toner.',100,1,'2026-08-13T00:00:00.000Z','["Covers Fujairah City, Dibba, Kalba, Khor Fakkan and Fujairah Free Trade Zone","FFTZ free-zone entity billing supported alongside mainland LLC invoicing","Zero deposit, unlimited genuine OEM toner, free delivery and network setup","Canon and Kyocera multifunction devices from AED 250/month"]'),
('qa-fjr-2','printer-rental-fujairah','How fast is emergency printer support in Fujairah?','Fujairah emergency response runs to a same-working-day target. Engineers dispatch from the Sharjah headquarters across the Sharjah-Fujairah road, so response is slower than the 60-minute Sharjah target but faster than a next-day service window. Consumable-life spare parts are carried on the vehicle so most faults resolve on the first visit.',101,1,'2026-08-13T00:00:00.000Z','["Same-working-day response target for Fujairah and the east coast","Engineers dispatch from the Sharjah HQ via the Sharjah-Fujairah road","Common spare parts carried on the service vehicle for first-visit fixes","Replacement machine supplied free if downtime would exceed 24 hours"]'),
('qa-fjr-3','printer-rental-fujairah','Can a Fujairah Free Trade Zone company be invoiced directly?','Yes. Sahara issues invoices to FFTZ-registered entities as well as mainland Fujairah LLCs, with documentation formatted for free-zone accounting and audit. Contracts can be held by the free-zone entity while equipment is delivered to any Fujairah site, including shared offices and warehouse facilities.',102,1,'2026-08-13T00:00:00.000Z','["FFTZ entity invoicing and mainland LLC invoicing both supported","Documentation formatted for free-zone accounting and audit requirements","Equipment deliverable to offices, warehouses and shared facilities","Zero deposit for qualified entities"]');

-- ── Printer Rental RAK (angle: RAK FTZ and free-zone billing) ──
INSERT OR IGNORE INTO faqs (id, pageSlug, question, answer, sortOrder, isActive, createdAt, supportingPoints) VALUES
('qa-rak-1','printer-rental-rak','Can a RAK free-zone company rent a printer from Sahara?','Yes. Sahara bills RAK free-zone entities directly. Rental printers and copiers are delivered to RAK Free Trade Zone, Al Hamra, Al Marjan Island, Al Nakheel, and RAK Industrial Area, with invoicing arranged to suit free-zone accounting. Plans start at AED 250 per month, zero deposit, toner included.',100,1,'2026-08-13T00:00:00.000Z','["RAK FTZ, Al Hamra, Al Marjan Island, Al Nakheel and RAK Industrial Area covered","Free-zone entity invoicing supported alongside mainland LLC billing","Zero deposit, unlimited genuine OEM toner, free delivery and network setup","Canon and Kyocera multifunction devices from AED 250/month"]'),
('qa-rak-2','printer-rental-rak','How much does printer rental cost in Ras Al Khaimah?','Printer rental in Ras Al Khaimah starts at AED 250 per month. That covers an A4 desktop machine; an A3 multifunction copier begins at AED 500. Delivery, installation, network setup, unlimited genuine OEM toner, and all maintenance are included. No deposit is required from qualified businesses.',101,1,'2026-08-13T00:00:00.000Z','["A4 desktop from AED 250/month; A3 multifunction from AED 500/month","Delivery, installation and network setup included at no charge","Unlimited genuine OEM toner included in every tier","Fleet discounts from three machines upward"]'),
('qa-rak-3','printer-rental-rak','Does a hotel or resort in RAK need a different rental setup?','Yes, usually. RAK hotels and Al Marjan Island resorts typically split machines between back-office administration and guest business centres, which have different volume profiles and security needs. Sahara configures secure print release for guest-facing units so documents only print when the guest is standing at the machine.',102,1,'2026-08-13T00:00:00.000Z','["Separate device tiers for back-office and guest business-centre use","Secure print release holds jobs until the user authenticates at the machine","Per-department billing so guest-services costs are tracked separately","Multi-property contracts consolidated under one agreement"]');

-- ── PaperCut Print Management (slug from migration 005) ──
INSERT OR IGNORE INTO faqs (id, pageSlug, question, answer, sortOrder, isActive, createdAt, supportingPoints) VALUES
('qa-pcut-1','papercut-print-management','What is the difference between PaperCut MF and PaperCut NG?','PaperCut MF embeds in the printer''s touch panel; PaperCut NG does not. MF suits enterprises running multifunction devices and tracks copy and scan activity as well as printing, licensed per device. NG suits workgroups of 1-50 users, tracks network printing only, and is licensed per user annually.',100,1,'2026-08-13T00:00:00.000Z','["MF: per-device licensing, embedded MFP touch-panel app, tracks print, copy and scan","NG: per-user annual licensing, network print tracking only","MF setup takes one to two days; NG installs in about half a day","Both include Mobility Print and Active Directory or LDAP integration"]'),
('qa-pcut-2','papercut-print-management','How does secure print release actually work?','Jobs are held on the server until the user authenticates at the printer. Staff send a document, walk to any enrolled machine, tap a card or enter a PIN, and the job prints only then. This removes uncollected output from printer trays, which is both a confidentiality risk and a large share of wasted paper.',101,1,'2026-08-13T00:00:00.000Z','["Jobs held at the server, released only after card or PIN authentication","Works across any enrolled machine, so users can collect at the nearest device","Eliminates uncollected prints left exposed in output trays","Unclaimed jobs auto-purge after a configurable timeout"]'),
('qa-pcut-3','papercut-print-management','How long does a PaperCut rollout take in a UAE office?','A PaperCut NG install takes about half a day. A multi-device MF rollout takes one to two days. That covers server installation, Active Directory or LDAP synchronisation, embedded app deployment to each multifunction device, policy configuration, and user training. Sahara then provides twelve months of remote and on-site support.',102,1,'2026-08-13T00:00:00.000Z','["NG: roughly half a day. MF multi-device: one to two days","Includes AD/LDAP sync, embedded app deployment, policy setup and user training","Twelve months of remote and on-site support included","Delivered across Dubai, Sharjah and Abu Dhabi"]');

-- ── Services: Paper Shredder Rental (new slug, services/ convention) ──
INSERT OR IGNORE INTO faqs (id, pageSlug, question, answer, sortOrder, isActive, createdAt, supportingPoints) VALUES
('qa-shr-1','services/paper-shredder-rental','What DIN security level do UAE offices need for confidential documents?','DIN P-4 is the standard recommended for confidential business documents. It produces cross-cut particles small enough that reconstruction is impractical, and satisfies UAE Personal Data Protection Law requirements for secure destruction. Sahara''s Fellowes Powershred rental range is DIN P-4 throughout, with higher P-5 and P-6 levels available on request.',100,1,'2026-08-13T00:00:00.000Z','["DIN P-4 cross-cut is the recommended level for confidential business documents","Meets UAE PDPL (Federal Decree-Law No. 45 of 2021) destruction requirements","P-5 and P-6 high-security models available on request","Entire Fellowes Powershred rental range is P-4 or above"]'),
('qa-shr-2','services/paper-shredder-rental','Which shredder size does an office of 20 people need?','A departmental shredder rated around 24 sheets per pass suits roughly 20 users. The Fellowes Powershred 325Ci fits that profile, with an 83-litre bin that avoids constant emptying and jam-proof feeding for mixed staff use. Smaller teams under 10 people are usually well served by the 10-sheet LX65.',101,1,'2026-08-13T00:00:00.000Z','["Fellowes Powershred 325Ci: 24 sheets per pass, 83L bin - from AED 400","Fellowes Powershred LX65: 10 sheets per pass, 22.7L bin - from AED 150","Bin capacity matters more than sheet rating for shared multi-user offices","Heavy-duty industrial models available for bulk clear-outs"]'),
('qa-shr-3','services/paper-shredder-rental','Is shredder maintenance included in the rental?','Yes. Servicing, repairs, and blade oiling are covered by the shredder rental fee, along with free delivery and on-site setup. Shredders that jam or lose cutting performance are serviced or swapped at no additional charge, which is the main practical advantage over buying a unit outright.',102,1,'2026-08-13T00:00:00.000Z','["Servicing, repairs and blade maintenance included in the rental fee","Free delivery and on-site setup across Dubai, Sharjah and Abu Dhabi","Machines swapped at no charge if performance degrades","Purchase price for comparison: AED 800-3,000 for an equivalent office unit"]'),
('qa-shr-4','services/paper-shredder-rental','Can Sahara shred documents on site rather than renting a machine?','Rental is the standard service - Sahara supplies the shredder, not a bureau. For a one-off office clear-out or compliance audit, a high-capacity unit can be rented short-term and collected afterwards, which usually costs less than an outsourced bureau for typical UAE office volumes.',103,1,'2026-08-13T00:00:00.000Z','["Short-term rental available for clear-outs, audits and office moves","High-capacity units supplied for bulk destruction jobs","Free delivery and collection at either end of the hire","Rental terms customised to volume - current rates confirmed same working day by phone"]');
