-- Seed FAQs for the three new PVC card printer intent pages
-- (services/pvc-card-printer-rental, services/pvc-card-printer-sales,
-- services/pvc-card-printing-services). Mirrors the DEFAULT_FAQS fallback
-- arrays in each page.tsx so D1 and the static fallback stay in sync.
-- Idempotent: INSERT OR REPLACE by id.

INSERT OR REPLACE INTO faqs (id, pageSlug, question, answer, isActive, sortOrder) VALUES
('pvc-rental-faq-1', 'services/pvc-card-printer-rental', 'Can I rent a PVC card printer for a single event in UAE?', 'Yes. Sahara offers short-term rental of the Bravo RTAI and DC 3300 for exhibitions, conferences, and one-off badge-printing needs — from a few days up to a full week, with on-site setup and same-day collection available across Dubai, Sharjah, and Abu Dhabi.', 1, 10),
('pvc-rental-faq-2', 'services/pvc-card-printer-rental', 'What is included in a PVC card printer rental?', 'Every rental includes the printer, a starter set of genuine ribbons, on-site delivery and setup, driver installation support, and phone/WhatsApp support for the rental period. Extended terms also include scheduled maintenance and a swap-out unit if a fault occurs.', 1, 20),
('pvc-rental-faq-3', 'services/pvc-card-printer-rental', 'What rental terms are available for card printers?', 'Weekly (events and exhibitions), monthly (onboarding drives, project-based ID issuance), and annual (ongoing badge programmes) — all as an authorised exclusive reseller of the Bravo RTAI and DC 3300 in the UAE, so genuine consumables are always in stock.', 1, 30),
('pvc-rental-faq-4', 'services/pvc-card-printer-rental', 'Is it cheaper to rent or buy a PVC card printer?', 'For a single event or a short project, rental avoids the upfront cost of a printer you''ll use once. For ongoing, regular card issuance — say, monthly new-hire badges — purchasing typically pays back within a year. See our rent-vs-buy comparison, or ask for a tailored recommendation.', 1, 40),
('pvc-rental-faq-5', 'services/pvc-card-printer-rental', 'Can a rented card printer encode access-control or RFID cards?', 'Yes — the Bravo DC 3300 rental unit can be configured with magnetic stripe, contact smartcard, or contactless/RFID encoding on request, useful for temporary access-badge programmes at conferences, free-zone facilities, or construction sites.', 1, 50),
('pvc-rental-faq-6', 'services/pvc-card-printer-rental', 'Do you deliver and set up the rental printer on-site?', 'Yes, delivery and setup are included across Dubai, Sharjah, Abu Dhabi, and all UAE emirates. Our technician configures the printer, installs drivers, and runs a test card before handover.', 1, 60),

('pvc-sales-faq-1', 'services/pvc-card-printer-sales', 'Where can I buy a genuine Bravo PVC card printer in UAE?', 'Sahara Office Equipments is the authorised exclusive reseller in the UAE for the Bravo RTAI and Bravo DC 3300 — the only UAE partner appointed by Bravo Global to sell, install, and warranty these two models. Buying through us guarantees a genuine unit, full 3-year warranty, and locally stocked consumables.', 1, 10),
('pvc-sales-faq-2', 'services/pvc-card-printer-sales', 'How much does a PVC card printer cost in UAE?', 'Indicative pricing starts around AED 5,000 for a Bravo DC 3300 S (simplex, no encoding) and ranges up to AED 22,000 for a Bravo RTAI with holographic security film. Final price depends on encoding modules, lamination, and simplex vs duplex — request a tailored quote for your exact configuration.', 1, 20),
('pvc-sales-faq-3', 'services/pvc-card-printer-sales', 'What warranty comes with a purchased Bravo card printer?', 'Both the RTAI and DC 3300 carry a 3-year printer warranty, with the RTAI additionally covering the print head for life. Optional extended warranty and an Annual Maintenance Contract (AMC) are available through Sahara as the authorised exclusive UAE reseller.', 1, 30),
('pvc-sales-faq-4', 'services/pvc-card-printer-sales', 'Can I upgrade a simplex DC 3300 to duplex after purchase?', 'Yes. The Bravo DC 3300 S (simplex) can be upgraded to duplex printing via a software activation key on-site — no hardware replacement needed. Ask your Sahara account manager when you order.', 1, 40),
('pvc-sales-faq-5', 'services/pvc-card-printer-sales', 'Do you supply genuine ribbons and blank cards after purchase?', 'Yes. As the authorised exclusive UAE reseller, Sahara stocks genuine YMCKO ribbons, retransfer film, and blank PVC/composite cards locally for same-day availability — see our Toner & Spare Parts page.', 1, 50),
('pvc-sales-faq-6', 'services/pvc-card-printer-sales', 'Is financing or leasing available for a card printer purchase?', 'We can structure a lease-to-own or staged-payment arrangement for larger orders, and pair a purchase with an AMC for predictable running costs. Contact us with your requirement for a tailored proposal.', 1, 60),

('pvc-print-svc-faq-1', 'services/pvc-card-printing-services', 'Can Sahara print my PVC cards without me buying a printer?', 'Yes. Our PVC card printing service handles the full job — artwork, printing, encoding, and lamination — on our own Bravo RTAI and DC 3300 printers, so you receive finished cards without buying or maintaining hardware.', 1, 10),
('pvc-print-svc-faq-2', 'services/pvc-card-printing-services', 'What card types can you print — beyond standard ID cards?', 'We print employee and student ID, visitor and contractor badges, access-control and RFID cards, membership and loyalty cards, gift cards, custom hologram cards, security cards (UV, microtext, tamper-evident), wooden cards, transparent/frosted cards, and rewritable cards.', 1, 20),
('pvc-print-svc-faq-3', 'services/pvc-card-printing-services', 'Can you print a custom hologram on our cards?', 'Yes — the Bravo RTAI applies both standard and fully custom holograms in-printer via retransfer film, without a separate laminator. Send your logo or security design and we''ll produce a proof before the full run.', 1, 30),
('pvc-print-svc-faq-4', 'services/pvc-card-printing-services', 'Do you print wooden or transparent PVC cards?', 'Yes. Specially treated wooden cards and transparent/frosted cards are supported on the Bravo RTAI — a distinctive option for premium membership cards, eco-conscious brands, or hospitality use.', 1, 40),
('pvc-print-svc-faq-5', 'services/pvc-card-printing-services', 'What is the minimum order quantity and turnaround time?', 'There is no strict minimum for standard ID cards; custom hologram and specialty-media orders (wooden, transparent) typically require a small minimum run. Standard turnaround is 2-3 business days after artwork approval; rush service is available.', 1, 50),
('pvc-print-svc-faq-6', 'services/pvc-card-printing-services', 'Can you encode access-control or RFID data during printing?', 'Yes — magnetic stripe (ISO 7811), contact smartcard, and contactless/RFID encoding are all available as part of the printing service, so your cards arrive ready to activate in your access-control system.', 1, 60);
